name: Actualizar Excel Automático

on:
  schedule:
    # Programado para las 10:45 AM Hora de Chile (14:45 UTC)
    - cron: '45 14 * * *'
  workflow_dispatch: # Mantiene el botón para ejecutar manualmente si quieres probarlo antes

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el código del repositorio
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar librerías
      run: |
        sudo apt-get update
        sudo apt-get install -y unixodbc-dev
        pip install pandas openpyxl sqlalchemy pyodbc requests

    - name: Ejecutar el script en la nube
      env:
        GITHUB_TOKEN: ${{ secrets.PRUEBAS_T }}
        DB_CONNECTION_STRING: ${{ secrets.CONEXION }}
      run: |
        python script.py
